@startuml
abstract class Figura{
+ {abstract} calcularArea(): double
+ mostrarArea(): void
}

class Circulo{
- radio: double
- PI : double = 3.141592

+ mostrarArea(): double
}

class Rectangulo{
- base: double
- altura: double

+ Rectangulo()
+ calcularArea(): double
}

Figura <|-- Circulo
Figura <|-- Rectangulo
@enduml